### ISSUE TITLE
Updated Script: wcofun-dl.py

### ISSUE THREAD

**Issue by TimmyRamone** [Nobody12here/WatchCartoonsOnline-Downloader#1]
I noticed the code wasn't working so I reworked it and it now works on wcofun.com.

I'm not sure how to create a pull request.  So if you want to see/use my version of this script you can find it attached to this note.

If you have any comments or questions, just let me know!

-TimmyRamone

[wcofun.zip](https://github.com/Nobody12here/WatchCartoonsOnline-Downloader/files/12135698/wcofun.zip)

**Comment by TimmyRamone** [comment]
Let's try that attachment again...

[wcofun.zip](https://github.com/Nobody12here/WatchCartoonsOnline-Downloader/files/12135679/wcofun.zip)

**Comment by Nobody12here** [comment]
Hey @TimmyRamone  Thanks for your help in updating the code. I will take a look at the code and i'll tell you how to create a pull requests. 
The script was abdanoned by me as I had lost intrest in it. Hopefully your contribution will spark my intrests and I'll be updating the code.

Thanks!

**Comment by Nobody12here** [comment]
Works perfectly fine

**Comment by TimmyRamone** [comment]
> Works perfectly fine

Glad to hear it!

One note: If the download is interrupted (as has happened to me a few times) just re-start the script in the same directory and it should skip the downloaded files and pick up where it left off.

**Comment by Nobody12here** [comment]
Added the updated code to the repo
